<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Rogue.Application\Rogue.Application.csproj" />
    <ProjectReference Include="..\Rogue.Data\Rogue.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dotnet-curses" Version="2.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
